### ISSUE TITLE
CPU version not working

### ISSUE THREAD

**Issue by peverati** [peterbjorgensen/DeepDFT#1]
I tried to run an instance to predict the density of a given molecule, but it failed because I don't have a GPU. I'm not trying to train the network, just to use the DeepDFT qm9 pretrained model to predict something. This is not working despite selecting --device cpu:

```
$ python predict_with_model.py --device cpu qm9_pretrained_model tst.xyz

Traceback (most recent call last):
  File "predict_with_model.py", line 168, in <module>
    main()
  File "predict_with_model.py", line 121, in main
    model, cutoff = load_model(args.model_dir, args.device)
  File "predict_with_model.py", line 45, in load_model
    state_dict = torch.load(os.path.join(model_dir, "best_model.pth"))
  File "/home/peve/anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/peve/anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 787, in _legacy_load
    result = unpickler.load()
  File "/home/peve/anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 743, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/home/peve/anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "/home/peve/anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 151, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/peve/anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 135, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

After adding 'map_location=torch.device('cpu')' ot the torch.load portion of the script, I can get past this first error, but yet there's another issue related to no GPU:

```
$ python predict_with_model.py --device cpu qm9_pretrained_model tst.xyz

/home/peve/anaconda3/lib/python3.8/site-packages/ase/utils/__init__.py:62: FutureWarning: Please use atoms.cell.cellpar() instead
  warnings.warn(warning)
2021-08-31 15:21:22,284 [DEBUG]  Computing atom-to-atom graph
Traceback (most recent call last):
  File "predict_with_model.py", line 168, in <module>
    main()
  File "predict_with_model.py", line 143, in main
    graph_dict = collate_fn([density_dict])
  File "/home/peve/DeepDFT/dataset.py", line 468, in __call__
    return collate_list_of_dicts(graphs, pin_memory=self.pin_memory)
  File "/home/peve/DeepDFT/dataset.py", line 419, in collate_list_of_dicts
    collated = {k: pin(pad_and_stack(dict_of_lists[k])) for k in dict_of_lists}
  File "/home/peve/DeepDFT/dataset.py", line 419, in <dictcomp>
    collated = {k: pin(pad_and_stack(dict_of_lists[k])) for k in dict_of_lists}
  File "/home/peve/DeepDFT/dataset.py", line 415, in <lambda>
    pin = lambda x: x.pin_memory()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```

Maybe it is really not possible to run on CPU, but then perhaps you should take the cpu flag out and specify it in the readme...

**Comment by peterbjorgensen** [comment]
Thanks for reporting, please update to the newest commit and let me know if it still doesn't work.

**Comment by peverati** [comment]
Works now, thank you!
Some debug warnings are printed (not sure if they are intended to be there, see below), but other than that, it seems very good!

```
2021-09-02 09:20:39,096 [DEBUG]  Written 1703000/20992660
2021-09-02 09:20:39,130 [DEBUG]  Written 1704000/20992660
2021-09-02 09:20:39,168 [DEBUG]  Written 1705000/20992660
2021-09-02 09:20:39,224 [DEBUG]  Written 1706000/20992660
2021-09-02 09:20:39,268 [DEBUG]  Written 1707000/20992660
2021-09-02 09:20:39,299 [DEBUG]  Written 1708000/20992660
2021-09-02 09:20:39,321 [DEBUG]  Written 1709000/20992660
2021-09-02 09:20:39,351 [DEBUG]  Written 1710000/20992660
2021-09-02 09:20:39,419 [DEBUG]  Written 1711000/20992660
2021-09-02 09:20:39,451 [DEBUG]  Written 1712000/20992660
2021-09-02 09:20:39,477 [DEBUG]  Written 1713000/20992660
2021-09-02 09:20:39,507 [DEBUG]  Written 1714000/20992660
2021-09-02 09:20:39,540 [DEBUG]  Written 1715000/20992660
2021-09-02 09:20:39,572 [DEBUG]  Written 1716000/20992660
2021-09-02 09:20:39,605 [DEBUG]  Written 1717000/20992660
2021-09-02 09:20:39,642 [DEBUG]  Written 1718000/20992660
2021-09-02 09:20:39,706 [DEBUG]  Written 1719000/20992660
```
